Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -1,18 +1,51 @@
-name: GitHub Actions Demo
-run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
-on: [push]
+name: Update Exchange Rates
+
+on:
+  schedule:
+    - cron: "0 6 1 * *"
+      timezone: "Europe/London"
+  workflow_dispatch:       
+
 jobs:
-  Explore-GitHub-Actions:
+  update-rates:
     runs-on: ubuntu-latest
+
     steps:
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      - name: Check out repository code
-        uses: actions/checkout@v6
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Set up R
+        uses: r-lib/actions/setup-r@v2
+        with:
+          r-version: '4.4.3'
+
+      - name: Install system dependencies
         run: |
-          ls ${{ github.workspace }}
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+          sudo apt-get update
+          sudo apt-get install -y \
+            libcurl4-openssl-dev \
+            libssl-dev \
+            libxml2-dev
+
+
+      - name: Install R packages
+        run: |
+          Rscript -e "install.packages(c('dplyr', 'openxlsx', 'readxl','rjson','jsonlite','janitor','gtools','httr','stringr','readr','tidyr','tibble','purrr'))"
+
+      - name: Run script
+        run: Rscript create-js/create_data.R
+
+      - name: Commit updated Excel file
+        run: |
+          git config user.name "github-actions"
+          git config user.email "actions@github.com"
+          git add -f data/"Exchange Rates for NIPS.xlsx"
+          git commit -m "Update exchange rates $(date +'%Y-%m')" || echo "No changes"
+          git push
+
+      - name: Notify on failure
+        if: failure()
+        run: |
+          echo "❌ Exchange rate update FAILED"
+          echo "Check logs in GitHub Actions"
+ 
